PATCH FILE - Borland C++ for Windows / Turbo C++ for Windows version 3.1
Object Browser

This patch corrects problems with browsing large programs in the Object
Browser of BCW 3.1 and TCW 3.1 by patching TBROWSER.DLL.


To use this patch, put all the files in this zipped file, 
except this readme.pat file, into the same directory as TBROWSER.DLL.

At the DOS prompt type PATINIT.  Hit return if you wish to continue,
CTRL-C if you wish to abort.

Borland Technical Support

